### PR TITLE
Allow symbols as handlers

### PR DESCRIPTION
**Pull request by naryl**

### CODE REVIEW

**Comment by spreadLink** [comment]
Hi,
This new pull request makes even less sense to me than the one before; After all, now you are just having a syntactical extension of allowing ' instead of just #'.

Can you please show me an example where your approach would be significantly different? I really have trouble understanding where exactly your problem is, and I'm hesitant to loosen the types for things I don't understand.

**Comment by naryl** [comment]
I provided the example after closing the previous commit. In short you got the function updated with add-event-handler right after defun but the old function definition will remain in handlers hash-table if you reevaluate defun without reevaluating add-event-handler.

**Comment by naryl** [comment]
```lisp
(defun some-handler ...)

(defun start-bot ()
  (setf *client* (make-bot (get-token)))
  (add-event-handler :event #'some-handler))
```

You can't redefine some-handler at all after this, and you also can't put add-event-handler in top-level because the *client* is undefined.

**Comment by spreadLink** [comment]
*CLIENT* should always be defined if you import lispcord, since it's a special variable which is automatically assigned to by MAKE-BOT (through SETF) and exported to the top-level. So explicitly SETFing it is redundant. 

That being said, I finally managed to get around testing the behaviour!
And you are right, once the EVENT-HANDLER is set it keeps a hold of the old function pointer. I wasn't aware of that behaviour at all, so thanks a lot for your patience explaining it to me :+1:

**Comment by naryl** [comment]
My bad, I meant unbound (EDIT: actually just nil), not undefined. You can't add handlers to *CLIENT* before the call to MAKE-BOT.

**Comment by naryl** [comment]
```lisp
(defun some-handler ...)
(add-event-handler :event #'some-handler) ; The value NIL is not of type LISPCORD.CORE:BOT

(defun start-bot ()
  (make-bot (get-token)))
```

**Pull request merged**
