### PR TITLE
Correct readme formatting

### PR DESCRIPTION
**Pull request by iddm**
Adds more highlighting and fixes some words.

### CODE REVIEW

**Comment by iddm** [comment]
Tried to help with it correcting the `README.md` a bit.

**Comment by spreadLink** [comment]
Nice, thanks

**Comment by iddm** [comment]
There are things I want to fix also, but I don't have a time right now. Will propose a PR some time later. Are you okay with that?

**Comment by spreadLink** [comment]
Ye sure.
There's a bunch of untested codepaths in the lib, and i unfortunately don't have time to give it the attention it needs i guess, so external help is very welcome :wink:

**Pull request merged**
