### PR TITLE
A few fixes

### PR DESCRIPTION
**Pull request by naryl**
1. E.g. to allow (defun start () (setf *bot* (make-bot ...))) without warnings
2. It just feels like a bug. Or should it be another function like maybe-remove-mention?

### CODE REVIEW

**Comment by naryl** [comment]
Hi, I'm accustomed to heavily interactive Lisp development. If it doesn't contradict project goals I'll send a few more patches to facilitate it. :)

**Comment by spreadLink** [comment]
Hi, can you quickly explain what the purpose of adding symbols as handlers would be? It is not exactly idiomatic modern style to fetch functions from symbols, so I really need a good reason to merge that.

Also, next time please don't just append more commits to the same pull-request; ATM I can only reject all your changes or merge all changes. You should open a commit for every topical change.

**Comment by naryl** [comment]
Yes, sorry about that. I intended the third commit to be a separate pull request but forgot that github adds it automatically if it's in the same branch.

I don't know about idiomatic modern style but it was idiomatic some time ago to not hold functions which are not declared anywhere in code. If you change a function definition everything should immediately forget the old definition and use the new one. And that's what the third commit does. Of course there's absolutely no difference if you don't develop interactively.

Actually it's not major for me personally since I'll have to wrap the handler facility anyway.

**Comment by naryl** [comment]
If you don't want to merge the third one, close the pull request and I'll recreate it properly.

**Comment by spreadLink** [comment]
Alright, so first of all I haven't thanked you yet for working on the lib, so thanks :)
Secondly, I object to the change in the example bot files of changing the hash-quotes to normal quotes simply because it makes the example a little bit more murky. MESSAGE-CREATE is an already defined function, and I'd like that to remain obvious.

Adding MAKE-BOT to the exports is fine and was in fact an oversight by me!

I'm still not clear what issues you are having with the function look ups. I developed and tested the library mostly interactively through slime, and never had issues with re-defined functions not being looked up correctly. CL should by definition make that look up on it's own, so the manual indirection through the symbol table seems odd to me. Can you give me a specific example where this is not working out for you?

I unfortunately can't really experiment with it today, and I haven't used the library in some time, but from the top of my head it really should work fine with the interactive development workflow, sans some possible thread issues which are not my fault.

Fast Edit: Maybe not my fault; I'm sure I made some mistakes there, too, but the ones I was referring to derive from the websocket library I am using.

**Comment by naryl** [comment]
Some folks on Discord showed me the better way to do it. I'll make two separate pull requests.

**Comment by spreadLink** [comment]
:+1:

**Comment by naryl** [comment]
Oh, the example. In the lispcord examples you have add-event-handler right next to defun and evaling them both will of course redefine the function, then replace the old definition with the new one in the handlers hash-table. If that add-event-handler is somewhere else and you don't call it right after defun then the hash-table will still have the old definition.

Folks on Discord said that's it's idiomatic to use functions (#'handler) most of the time and only use symbols when you need to stress that this handler is redefinable. So if you need it refedinable it's more idiomatic to store a symbol instead of evaluating add-event-handler every time right after defun. But otherwise #' is more idiomatic so it indeed has to stay in all examples as the default way.

**Pull request closed without merging**
